<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>swarm_bringup</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="elghali@todo.todo">elghali</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <exec_depend>swarm_controller</exec_depend>
  <exec_depend>swarm_filter</exec_depend>
  <exec_depend>swarm_marvelmind</exec_depend>
  <exec_depend>swarm_nav2_controller</exec_depend>
  <exec_depend>swarm_dwb_critics</exec_depend>
  <exec_depend>swarm_kalman_filter</exec_depend>
  <exec_depend>swarm_spacecraft</exec_depend>
  <exec_depend>robomaster_ros</exec_depend>
  <exec_depend>dwb_core</exec_depend>
  <exec_depend>dwb_critics</exec_depend>
  <exec_depend>dwb_plugins</exec_depend>
  <exec_depend>nav2_common</exec_depend>
  <exec_depend>nav2_controller</exec_depend>
  <exec_depend>nav2_lifecycle_manager</exec_depend>
  <exec_depend>nav2_velocity_smoother</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
