---
- name: Deploy RoboMaster Swarm Node
  hosts: robots
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        name:
          - docker.io
          - python3-pip
          - python3-rpi.gpio
          - git
          - libopus-dev
        state: present

    - name: Ensure docker service is running
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Install docker Python module for Ansible
      pip:
        name: docker

    - name: Ensure gpio group exists
      group:
        name: gpio
        state: present

    - name: Ensure dialout group exists
      group:
        name: dialout
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Add user to gpio group
      user:
        name: "{{ ansible_user }}"
        groups: gpio
        append: yes

    - name: Add user to dialout group
      user:
        name: "{{ ansible_user }}"
        groups: dialout
        append: yes

    - name: Create GPIO udev rules
      copy:
        dest: /etc/udev/rules.d/99-gpio.rules
        content: |
          SUBSYSTEM=="gpio*", GROUP="gpio", MODE="770"
          SUBSYSTEM=="pwm*", GROUP="gpio", MODE="770"
          KERNEL=="spidev*", GROUP="gpio", MODE="660"
          KERNEL=="i2c-[0-9]*", GROUP="gpio", MODE="660"
          KERNEL=="ttyAMA[0-9]*", GROUP="gpio", MODE="660"
          KERNEL=="gpiomem", GROUP="gpio", MODE="660"

    - name: Reload udev rules
      command: udevadm control --reload-rules

    - name: Trigger udev
      command: udevadm trigger

    - name: Pull swarm Docker image
      community.docker.docker_image:
        name: elghaliasri/ros2-humble-swarm:robot-arm64-v1
        source: pull

    - name: Run swarm container
      community.docker.docker_container:
        name: "{{ inventory_hostname }}"
        image: elghaliasri/ros2-humble-swarm:robot-arm64-v1
        state: started
        restart_policy: always
        privileged: yes
        network_mode: host
        devices:
          - /dev/gpiomem
          - /dev/ttyUSB0
          - /dev/ttyUSB1
          - /dev/ttyAMA0

    - name: Reboot robot to apply group changes
      reboot:
        reboot_timeout: 300
