---
- name: Validate RoboMaster fleet
  hosts: robots
  become: yes
  gather_facts: false
  strategy: free

  vars_files:
    - vars.yml

  tasks:

    - name: Load expected runtime configuration
      ansible.builtin.include_tasks: tasks/runtime_config.yml

    - name: Validate deployment
      ansible.builtin.include_tasks: tasks/validate.yml
