[robots]
robot1 ansible_host=192.168.1.101 ansible_user=raspberrypi ansible_ssh_private_key_file=~/.ssh/ansible ansible_become_password=robomaster

[robots:vars]
; ansible_user=raspberrypi
ansible_ssh_private_key_file=~/.ssh/ansible