[robots]
robot1 ansible_host=192.168.1.101 ansible_user=raspberrypi ansible_become_password=robomaster robot_idx=1

; robot2 ansible_host=192.168.1.102 ansible_user=jason ansible_become_password=1234 robot_idx=2
; robot3 ansible_host=192.168.1.103 ansible_user=raspberrypi3 ansible_become_password=robomaster robot_idx=3

robot4 ansible_host=192.168.1.104 ansible_user=robomaster1 ansible_become_password=robomaster1 robot_idx=4

[robots:vars]
ansible_ssh_private_key_file=~/.ssh/ansible
ansible_python_interpreter=/usr/bin/python3